
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class ApplyForm extends javax.swing.JFrame {

    /**
     * Creates new form ApplyForm
     */
    Connection c=null;
    PreparedStatement p=null;
    int r=0;
    
    public ApplyForm() {
        initComponents();
        c=ConnectDB.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        block = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        area = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dist = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        cpass = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Application form for user");

        jPanel1.setLayout(null);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 20, 80, 70);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Application form for new user");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 110, 200, 20);

        jLabel1.setText("First Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 140, 80, 14);
        jPanel1.add(fname);
        fname.setBounds(180, 170, 110, 30);

        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 140, 70, 14);

        lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameActionPerformed(evt);
            }
        });
        jPanel1.add(lname);
        lname.setBounds(350, 170, 100, 30);

        jLabel5.setText("Block/Apartment");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(370, 230, 90, 30);
        jPanel1.add(block);
        block.setBounds(470, 230, 150, 30);

        jLabel6.setText("Area/Landmark");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(370, 270, 90, 30);
        jPanel1.add(area);
        area.setBounds(470, 270, 150, 30);

        jLabel7.setText("District");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(370, 320, 70, 14);
        jPanel1.add(dist);
        dist.setBounds(470, 310, 150, 30);

        jLabel8.setText("PIN");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(370, 360, 50, 14);

        pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinActionPerformed(evt);
            }
        });
        jPanel1.add(pin);
        pin.setBounds(470, 350, 150, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submit copy (1).jpg"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(220, 420, 80, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear (1).jpg"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(350, 420, 70, 30);

        jLabel9.setText("User ID");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 230, 50, 30);
        jPanel1.add(userid);
        userid.setBounds(160, 230, 130, 30);

        jLabel10.setText("Password");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 270, 60, 30);

        jLabel11.setText("Confrim Password");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 310, 110, 30);
        jPanel1.add(pass);
        pass.setBounds(160, 270, 130, 30);
        jPanel1.add(cpass);
        cpass.setBounds(160, 310, 130, 30);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/apply (1).jpg"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 0, 630, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql="insert into customer(user_id,password,phone_no,fname,lname,block,area,district,pin) values(?,?,0,?,?,?,?,?,?)";
        String s1,s2;
        s1=pass.getText();
        s2=cpass.getText();
        try{
                p=c.prepareStatement(sql);
                p.setString(1,userid.getText());
                p.setString(2,pass.getText());
                p.setString(3,fname.getText());
                p.setString(4,lname.getText());
                p.setString(5,block.getText());
                p.setString(6,area.getText());
                p.setString(7,dist.getText());
                p.setString(8,pin.getText());
                if(s1.equals(s2))
                {
                    r=p.executeUpdate();
                    if(r!=0)
                    {
                        this.dispose();
                        r=0;
                        p.close();
                        c.close();
                        JOptionPane.showMessageDialog(null,"Apply Succesfull");
                        
                        
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Apply Failed");
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Please check password");
                }
            
                
                
                
                
            
        }
        catch(SQLException | HeadlessException xe)
        {
            JOptionPane.showMessageDialog(null,xe);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fname.setText("");
        lname.setText("");
        userid.setText("");
        pass.setText("");
        cpass.setText("");
        block.setText("");
        area.setText("");
        dist.setText("");
        pin.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApplyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApplyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApplyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApplyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApplyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField area;
    private javax.swing.JTextField block;
    private javax.swing.JPasswordField cpass;
    private javax.swing.JTextField dist;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField pin;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables
}
