
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Font;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class BillingDetails extends javax.swing.JFrame {

    /**
     * Creates new form BillingDetails
     */
    Connection c=null;
    PreparedStatement p=null;
    ResultSet re=null;
    public BillingDetails() {
        initComponents();
    }
    public BillingDetails(ResultSet r)
    {
        initComponents();
        c=ConnectDB.connect();
        try{
            telephone.setText(r.getString("phone_no"));
            custid.setText(r.getString("user_id"));
            fname.setText(r.getString("fname"));
            lname.setText(r.getString("lname"));
            block.setText(r.getString("block"));
            area.setText(r.getString("area"));
            district.setText(r.getString("district"));
            pin.setText(r.getString("pin"));
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        telephone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        custid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        block = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        area = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        district = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pin = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tminutes = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        hour = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tdata = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        fd = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cpc = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        noc = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        fc = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cpm = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        netcall = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        netdata = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        callcharge = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        netdatacost = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        servicetax = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tamount = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        fixedcharge = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        month = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        bill = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Billing Details");

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Telephone Number");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 40, 120, 15);
        jPanel1.add(telephone);
        telephone.setBounds(40, 70, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Customer ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 40, 100, 15);

        custid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custidActionPerformed(evt);
            }
        });
        jPanel1.add(custid);
        custid.setBounds(220, 70, 120, 30);

        jLabel3.setText("Customer Details");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 120, 120, 20);

        jLabel5.setText("First Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 160, 130, 14);
        jPanel1.add(fname);
        fname.setBounds(40, 180, 150, 30);

        jLabel6.setText("Last Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 160, 100, 14);
        jPanel1.add(lname);
        lname.setBounds(230, 180, 110, 30);

        jLabel7.setText("Block/Flat");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 230, 60, 30);

        block.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blockActionPerformed(evt);
            }
        });
        jPanel1.add(block);
        block.setBounds(140, 230, 200, 30);

        jLabel8.setText("Area/Landmark");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(50, 280, 90, 30);
        jPanel1.add(area);
        area.setBounds(140, 280, 190, 30);

        jLabel9.setText("Distict");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 330, 40, 30);
        jPanel1.add(district);
        district.setBounds(140, 330, 140, 30);

        jLabel4.setText("PIN");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 380, 40, 30);
        jPanel1.add(pin);
        pin.setBounds(140, 380, 140, 30);

        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel10);
        jLabel10.setBounds(20, 140, 340, 370);

        jLabel11.setText("Billing Details");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel11);
        jLabel11.setBounds(400, 120, 90, 20);

        jLabel12.setText("Total Minutes");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(410, 230, 80, 30);
        jPanel1.add(tminutes);
        tminutes.setBounds(510, 230, 90, 30);

        jLabel13.setText("Total Hour");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(410, 280, 80, 14);

        hour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourActionPerformed(evt);
            }
        });
        jPanel1.add(hour);
        hour.setBounds(510, 270, 90, 30);

        jLabel14.setText("Total Data(Mb)");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(410, 320, 90, 14);

        tdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdataActionPerformed(evt);
            }
        });
        jPanel1.add(tdata);
        tdata.setBounds(510, 310, 70, 30);

        jLabel15.setText("Free Data(Mb)");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(630, 230, 80, 30);

        fd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdActionPerformed(evt);
            }
        });
        jPanel1.add(fd);
        fd.setBounds(720, 230, 90, 30);

        jLabel16.setText("Cost Per Call");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(630, 280, 90, 30);
        jPanel1.add(cpc);
        cpc.setBounds(720, 280, 90, 30);

        jLabel17.setText("No of Calls");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(410, 350, 80, 30);

        noc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nocActionPerformed(evt);
            }
        });
        jPanel1.add(noc);
        noc.setBounds(510, 350, 60, 30);

        jLabel18.setText("Free Calls");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(630, 180, 60, 30);
        jPanel1.add(fc);
        fc.setBounds(720, 180, 90, 30);

        jLabel19.setText("Cost/Mb");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(630, 330, 70, 30);
        jPanel1.add(cpm);
        cpm.setBounds(720, 330, 90, 30);

        jLabel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel20);
        jLabel20.setBounds(400, 140, 430, 260);

        jLabel21.setText("Net. Calls");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(470, 420, 70, 14);
        jPanel1.add(netcall);
        netcall.setBounds(530, 410, 90, 30);

        jLabel22.setText("Net Data");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(470, 450, 50, 30);
        jPanel1.add(netdata);
        netdata.setBounds(530, 450, 90, 30);

        jLabel23.setText("Net. Calls Charge");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(640, 410, 110, 30);
        jPanel1.add(callcharge);
        callcharge.setBounds(740, 410, 80, 30);

        jLabel24.setText("Net. Data Cost");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(640, 450, 90, 30);
        jPanel1.add(netdatacost);
        netdatacost.setBounds(740, 450, 80, 30);

        jLabel25.setText("Service Tax.");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(640, 500, 80, 14);
        jPanel1.add(servicetax);
        servicetax.setBounds(740, 490, 80, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Payble Amount");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(630, 580, 90, 30);

        tamount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(tamount);
        tamount.setBounds(740, 580, 80, 30);

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(610, 570, 230, 50);

        jLabel28.setText("Fixed Charge");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(640, 530, 90, 30);
        jPanel1.add(fixedcharge);
        fixedcharge.setBounds(740, 530, 80, 30);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 630, 57, 23);

        month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "November", "October", "September" }));
        jPanel1.add(month);
        month.setBounds(370, 70, 120, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ok (1).jpg"))); // NOI18N
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(630, 70, 50, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Month");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(370, 40, 80, 14);
        jPanel1.add(bill);
        bill.setBounds(540, 160, 60, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Bill ID");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(490, 170, 32, 14);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/final page (1).jpg"))); // NOI18N
        jPanel1.add(jLabel27);
        jLabel27.setBounds(0, 0, 880, 690);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 883, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void custidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custidActionPerformed

    private void blockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blockActionPerformed

    private void tdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdataActionPerformed

    private void fdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fdActionPerformed

    private void nocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nocActionPerformed

    private void hourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        File nFile=new File(System.getProperty("user.home"));
        Document doc=new Document(PageSize.A6,5,5,5,5);
        try{
            PdfWriter writer=PdfWriter.getInstance(doc,new FileOutputStream(nFile+"\\Desktop\\TBill"+custid.getText()+".pdf"));
            doc.open();
            doc.add(new Paragraph("--------------- AKD TELECOM SERVICE -----------",FontFactory.getFont(BaseFont.COURIER_BOLD,10)));
            doc.add(new Paragraph("---------------------------------------------------------------------"));
            PdfPTable nBillingData=new PdfPTable(3);
            PdfPCell nTableCell=new PdfPCell();
            nBillingData.setWidthPercentage(95);
            nBillingData.setWidths(new int[]{30,40,20});
            Font nFont=FontFactory.getFont(BaseFont.COURIER_BOLD,10);
            
            nTableCell=new PdfPCell(new Phrase("Phone: ",nFont));
            nTableCell.setBorder(Rectangle.NO_BORDER);
            nBillingData.addCell(nTableCell);
            
            nTableCell=new PdfPCell(new Phrase("Customer ID: ",nFont));
            nTableCell.setBorder(Rectangle.NO_BORDER);
            nBillingData.addCell(nTableCell);
            
            nTableCell=new PdfPCell(new Phrase("Bill ID",nFont));
            nTableCell.setBorder(Rectangle.NO_BORDER);
            nBillingData.addCell(nTableCell);
            
            nTableCell=new PdfPCell(new Phrase(telephone.getText(),nFont));
            nTableCell.setBorder(Rectangle.NO_BORDER);
            nBillingData.addCell(nTableCell);
            
            nTableCell=new PdfPCell(new Phrase(custid.getText(),nFont));
            nTableCell.setBorder(Rectangle.NO_BORDER);
            nBillingData.addCell(nTableCell);
            
            nTableCell=new PdfPCell(new Phrase(bill.getText(),nFont));
            nTableCell.setBorder(Rectangle.NO_BORDER);
            nBillingData.addCell(nTableCell);
            
            doc.add(nBillingData);
            doc.add(new Paragraph("----------------CUSTOMER DETAILS---------------",FontFactory.getFont(BaseFont.COURIER_BOLD,10)));
            
            PdfPTable nCustDetails=new PdfPTable(2);
            PdfPCell nCustDetailsCell=new PdfPCell();
            nCustDetails.setWidthPercentage(95);
            nCustDetails.setWidths(new int[]{40,70});
            
            nCustDetailsCell=new PdfPCell(new Phrase("Customer Name: ",nFont));
            nCustDetailsCell.setBorder(Rectangle.NO_BORDER);
            nCustDetails.addCell(nCustDetailsCell);
            
            nCustDetailsCell=new PdfPCell(new Phrase(fname.getText()+" "+lname.getText(),nFont));
            nCustDetailsCell.setBorder(Rectangle.NO_BORDER);
            nCustDetails.addCell(nCustDetailsCell);
            
            nCustDetailsCell=new PdfPCell(new Phrase("Address: ",nFont));
            nCustDetailsCell.setBorder(Rectangle.NO_BORDER);
            nCustDetails.addCell(nCustDetailsCell);
            
            nCustDetailsCell=new PdfPCell(new Phrase(block.getText()+", "+area.getText()+", "+district.getText()+", "+pin.getText(),nFont));
            nCustDetailsCell.setBorder(Rectangle.NO_BORDER);
            nCustDetails.addCell(nCustDetailsCell);
            
            doc.add(nCustDetails);
            doc.add(new Paragraph("---------------- BILLING DETAILS -------------",FontFactory.getFont(BaseFont.COURIER_BOLD,10)));
            
            PdfPTable nDataTable=new PdfPTable(2);
            PdfPCell nDataTableCell=new PdfPCell();
            nDataTable.setWidthPercentage(95);
            nDataTable.setWidths(new int[]{40,55});
            /*------------------------------------------------------------------*/
            nDataTableCell=new PdfPCell(new Phrase("Total Minutes: ",nFont));
            nDataTableCell.setBorder(Rectangle.NO_BORDER);
            
            nDataTable.addCell(nDataTableCell);
            
            nDataTableCell=new PdfPCell(new Phrase(tminutes.getText(),nFont));
            nDataTableCell.setBorder(Rectangle.NO_BORDER);
            nDataTableCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            nDataTable.addCell(nDataTableCell);
            
            nDataTableCell=new PdfPCell(new Phrase("Total Hour: ",nFont));
            nDataTableCell.setBorder(Rectangle.NO_BORDER);
            
            nDataTable.addCell(nDataTableCell);
            
            nDataTableCell=new PdfPCell(new Phrase(hour.getText(),nFont));
            nDataTableCell.setBorder(Rectangle.NO_BORDER);
            nDataTableCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            nDataTable.addCell(nDataTableCell);
            
            nDataTableCell=new PdfPCell(new Phrase("Total Data: ",nFont));
            nDataTableCell.setBorder(Rectangle.NO_BORDER);
            
            nDataTable.addCell(nDataTableCell);
            
            nDataTableCell=new PdfPCell(new Phrase(tdata.getText(),nFont));
            nDataTableCell.setBorder(Rectangle.NO_BORDER);
            nDataTableCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            nDataTable.addCell(nDataTableCell);
            
            nDataTableCell=new PdfPCell(new Phrase("No of Calls: ",nFont));
            nDataTableCell.setBorder(Rectangle.NO_BORDER);
            
            nDataTable.addCell(nDataTableCell);
            
            nDataTableCell=new PdfPCell(new Phrase(noc.getText(),nFont));
            nDataTableCell.setBorder(Rectangle.NO_BORDER);
            nDataTableCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            nDataTable.addCell(nDataTableCell);
            /*------------------------------------------------------------------*/
            nDataTableCell=new PdfPCell(new Phrase("Free Calls: ",nFont));
            nDataTableCell.setBorder(Rectangle.NO_BORDER);
            
            nDataTable.addCell(nDataTableCell);
            
            nDataTableCell=new PdfPCell(new Phrase(fc.getText(),nFont));
            nDataTableCell.setBorder(Rectangle.NO_BORDER);
            nDataTableCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            nDataTable.addCell(nDataTableCell);
            
            nDataTableCell=new PdfPCell(new Phrase("Free Data: ",nFont));
            nDataTableCell.setBorder(Rectangle.NO_BORDER);
            
            nDataTable.addCell(nDataTableCell);
            
            nDataTableCell=new PdfPCell(new Phrase(fd.getText(),nFont));
            nDataTableCell.setBorder(Rectangle.NO_BORDER);
            nDataTableCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            nDataTable.addCell(nDataTableCell);
            
            nDataTableCell=new PdfPCell(new Phrase("Cost Per Call: ",nFont));
            nDataTableCell.setBorder(Rectangle.NO_BORDER);
            
            nDataTable.addCell(nDataTableCell);
            
            nDataTableCell=new PdfPCell(new Phrase(cpc.getText(),nFont));
            nDataTableCell.setBorder(Rectangle.NO_BORDER);
            nDataTableCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            nDataTable.addCell(nDataTableCell);
            
            nDataTableCell=new PdfPCell(new Phrase("Cost per MB: ",nFont));
            nDataTableCell.setBorder(Rectangle.NO_BORDER);
            
            nDataTable.addCell(nDataTableCell);
            
            nDataTableCell=new PdfPCell(new Phrase(cpm.getText(),nFont));
            nDataTableCell.setBorder(Rectangle.NO_BORDER);
            nDataTableCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            nDataTable.addCell(nDataTableCell);
            
            doc.add(nDataTable);
            doc.add(new Paragraph("-----------------------------------------------------------------------"));
            
            PdfPTable nNetBillingTable=new PdfPTable(4);
            PdfPCell nNetBillingTableCell=new PdfPCell();
            nNetBillingTable.setWidthPercentage(95);
            nNetBillingTable.setWidths(new int[]{25,15,40,15});
            
            
            nNetBillingTableCell= new PdfPCell(new Phrase("Net Calls : ",nFont));
            nNetBillingTableCell.setBorder(Rectangle.NO_BORDER);
            nNetBillingTable.addCell(nNetBillingTableCell);
            
            nNetBillingTableCell= new PdfPCell(new Phrase(netcall.getText(),nFont));
            nNetBillingTableCell.setBorder(Rectangle.NO_BORDER);
            nNetBillingTable.addCell(nNetBillingTableCell);
            
            nNetBillingTableCell= new PdfPCell(new Phrase("Net Calls Cost : ",nFont));
            nNetBillingTableCell.setBorder(Rectangle.NO_BORDER);
            nNetBillingTable.addCell(nNetBillingTableCell);
            
            nNetBillingTableCell= new PdfPCell(new Phrase(callcharge.getText(),nFont));
            nNetBillingTableCell.setBorder(Rectangle.NO_BORDER);
            nNetBillingTable.addCell(nNetBillingTableCell);
            
            nNetBillingTableCell= new PdfPCell(new Phrase("Net Data : ",nFont));
            nNetBillingTableCell.setBorder(Rectangle.NO_BORDER);
            nNetBillingTable.addCell(nNetBillingTableCell);
            
            nNetBillingTableCell= new PdfPCell(new Phrase(netdata.getText(),nFont));
            nNetBillingTableCell.setBorder(Rectangle.NO_BORDER);
            nNetBillingTable.addCell(nNetBillingTableCell);
            
            nNetBillingTableCell= new PdfPCell(new Phrase("Net Data Cost : ",nFont));
            nNetBillingTableCell.setBorder(Rectangle.NO_BORDER);
            nNetBillingTable.addCell(nNetBillingTableCell);
            
            nNetBillingTableCell= new PdfPCell(new Phrase(netdatacost.getText(),nFont));
            nNetBillingTableCell.setBorder(Rectangle.NO_BORDER);
            nNetBillingTable.addCell(nNetBillingTableCell);
            
            nNetBillingTableCell= new PdfPCell(new Phrase("",nFont));
            nNetBillingTableCell.setBorder(Rectangle.NO_BORDER);
            nNetBillingTable.addCell(nNetBillingTableCell);
            
            
            nNetBillingTableCell= new PdfPCell(new Phrase("",nFont));
            nNetBillingTableCell.setBorder(Rectangle.NO_BORDER);
            nNetBillingTable.addCell(nNetBillingTableCell);
            
            
            nNetBillingTableCell= new PdfPCell(new Phrase("Service Tax : ",nFont));
            nNetBillingTableCell.setBorder(Rectangle.NO_BORDER);
            nNetBillingTable.addCell(nNetBillingTableCell);
            
            nNetBillingTableCell= new PdfPCell(new Phrase(servicetax.getText(),nFont));
            nNetBillingTableCell.setBorder(Rectangle.NO_BORDER);
            nNetBillingTable.addCell(nNetBillingTableCell);
            
            nNetBillingTableCell= new PdfPCell(new Phrase("",nFont));
            nNetBillingTableCell.setBorder(Rectangle.NO_BORDER);
            nNetBillingTable.addCell(nNetBillingTableCell);
            
            
            nNetBillingTableCell= new PdfPCell(new Phrase("",nFont));
            nNetBillingTableCell.setBorder(Rectangle.NO_BORDER);
            nNetBillingTable.addCell(nNetBillingTableCell);
            
            nNetBillingTableCell= new PdfPCell(new Phrase("Fixed Charge : ",nFont));
            nNetBillingTableCell.setBorder(Rectangle.NO_BORDER);
            nNetBillingTable.addCell(nNetBillingTableCell);
            
            nNetBillingTableCell= new PdfPCell(new Phrase(fixedcharge.getText(),nFont));
            nNetBillingTableCell.setBorder(Rectangle.NO_BORDER);
            nNetBillingTable.addCell(nNetBillingTableCell);
            
            doc.add(nNetBillingTable);
            doc.add(new Paragraph("-----------------------------------------------------------------------"));
             
            PdfPTable nPaybleAmountTable=new PdfPTable(2);
            PdfPCell nPaybleAPdfPCell=new PdfPCell();
            nPaybleAmountTable.setWidthPercentage(50);
            nPaybleAmountTable.setHorizontalAlignment(Element.ALIGN_RIGHT);
            nPaybleAmountTable.setWidths(new int[]{25,25});
            
            nPaybleAPdfPCell=new PdfPCell(new Phrase("Payble Amount: ",nFont));
            nPaybleAPdfPCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            nPaybleAPdfPCell.setBorder(Rectangle.NO_BORDER);
            nPaybleAmountTable.addCell(nPaybleAPdfPCell);
            
            nPaybleAPdfPCell=new PdfPCell(new Phrase(tamount.getText(),nFont));
            nPaybleAPdfPCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
            nPaybleAPdfPCell.setBorder(Rectangle.NO_BORDER);
            nPaybleAmountTable.addCell(nPaybleAPdfPCell);
            
            doc.add(nPaybleAmountTable);
            
            doc.close();
            writer.close();
        }
        catch(FileNotFoundException | DocumentException error)
        {
            JOptionPane.showMessageDialog(null,error);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        try{
            String query;
            String s=(String)month.getSelectedItem();
            if(s.equals("November"))
            {
                 query="select * from November where user_id=?";
            }
            else if(s.equals("October"))
            {
                 query="select * from October where user_id=?";
            }
            else
            {
                 query="select * from September where user_id=?";
            }
            p=c.prepareStatement(query);
            p.setString(1,custid.getText());
            re=p.executeQuery();
            if(re.next())
            {
                bill.setText(re.getString("bill_id"));
                tminutes.setText(re.getString("tmin"));
                tdata.setText(re.getString("tdata"));
                noc.setText(re.getString("no_of_calls"));
                String hr=tminutes.getText();
                Float f1=(Float.parseFloat(hr))/60;
                hour.setText(""+f1);
                fc.setText("1200");
                fd.setText("5120");
                cpc.setText("0.5");
                cpm.setText("0.1");
                Float f2=Float.parseFloat(tminutes.getText());
                Float f3=Float.parseFloat(fc.getText());
                float f4=f2-f3;
                if(f4>0)
                {
                    netcall.setText(""+f4);
                }
                else
                {
                    netcall.setText("0");
                }
                Float f5=Float.parseFloat(tdata.getText());
                Float f6=Float.parseFloat(fd.getText());
                float f7=f5-f6;
                if(f7>0)
                {
                    netdata.setText(""+f7);
                }
                else
                {
                    netdata.setText("0");
                }
                Float f8=Float.parseFloat(cpc.getText());
                Float f9=Float.parseFloat(netcall.getText());
                float f10=f8*f9;
                callcharge.setText(""+f10);
                Float f11=Float.parseFloat(cpm.getText());
                Float f12=Float.parseFloat(netdata.getText());
                float f13=f11*f12;
                netdatacost.setText(""+f13);
                servicetax.setText("3.5");
                fixedcharge.setText("150");
                Float f14=Float.parseFloat(servicetax.getText());
                Float f15=Float.parseFloat(fixedcharge.getText());
                float total=f10+f13+f14+f15;
                tamount.setText(""+total);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Error");
            }
            
            
        }
        catch(SQLException X)
        {
            JOptionPane.showMessageDialog(null,X);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField area;
    private javax.swing.JTextField bill;
    private javax.swing.JTextField block;
    private javax.swing.JTextField callcharge;
    private javax.swing.JTextField cpc;
    private javax.swing.JTextField cpm;
    private javax.swing.JTextField custid;
    private javax.swing.JTextField district;
    private javax.swing.JTextField fc;
    private javax.swing.JTextField fd;
    private javax.swing.JTextField fixedcharge;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField hour;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lname;
    private javax.swing.JComboBox month;
    private javax.swing.JTextField netcall;
    private javax.swing.JTextField netdata;
    private javax.swing.JTextField netdatacost;
    private javax.swing.JTextField noc;
    private javax.swing.JTextField pin;
    private javax.swing.JTextField servicetax;
    private javax.swing.JTextField tamount;
    private javax.swing.JTextField tdata;
    private javax.swing.JTextField telephone;
    private javax.swing.JTextField tminutes;
    // End of variables declaration//GEN-END:variables
}
