
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class NoRegister extends javax.swing.JFrame {

    /**
     * Creates new form NoRegister
     */
    Connection co=null;
    PreparedStatement ps=null,p=null;
    int re=0;
    int res=0;
    public NoRegister() {
        initComponents();
        co=ConnectDB.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        td = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tnc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Number Ragistration");

        jPanel1.setLayout(null);

        jLabel2.setText("User ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 20, 90, 30);
        jPanel1.add(uid);
        uid.setBounds(260, 20, 160, 30);

        jLabel3.setText("Telephone No.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 70, 110, 30);

        tno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnoActionPerformed(evt);
            }
        });
        jPanel1.add(tno);
        tno.setBounds(260, 70, 160, 30);

        jLabel4.setText("Total Minutes");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 120, 110, 30);
        jPanel1.add(tm);
        tm.setBounds(260, 120, 70, 30);

        jLabel5.setText("Total Data");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(140, 170, 60, 30);
        jPanel1.add(td);
        td.setBounds(260, 170, 70, 30);

        jLabel6.setText("No of Calls");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(140, 220, 80, 30);
        jPanel1.add(tnc);
        tnc.setBounds(260, 220, 70, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submit copy (1).jpg"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(370, 270, 80, 30);

        jLabel1.setText("Month");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 270, 60, 30);

        combobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "November", "October", "September" }));
        jPanel1.add(combobox);
        combobox.setBounds(260, 270, 90, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newc (1).jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 480, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         // TODO add your handling code here:
        DateFormat nBillId=new SimpleDateFormat("MMss");
        java.util.Date nSysDate = new java.util.Date();
        String combo=(String)combobox.getSelectedItem();
        String qry;
        String sq="update customer set phone_no=? where user_id=?";
        try{
            p=co.prepareStatement(sq);
            p.setString(1,tno.getText());
            p.setString(2,uid.getText());
            re=p.executeUpdate();
        }
        catch(SQLException x)
        {
            JOptionPane.showMessageDialog(null,x);
        }
        try{
            if(combo.equals("November"))
            {
                qry="insert into November(bill_id,user_id,phone_no,tmin,tdata,no_of_calls) values(?,?,?,?,?,?)";
            }
            else if(combo.equals("October"))
            {
                qry="insert into October(bill_id,user_id,phone_no,tmin,tdata,no_of_calls) values(?,?,?,?,?,?)";
            }
            else
            {
                qry="insert into September(bill_id,user_id,phone_no,tmin,tdata,no_of_calls) values(?,?,?,?,?,?)";
            }
            
            ps=co.prepareStatement(qry);
            ps.setString(2,uid.getText());
            ps.setString(3,tno.getText());
            ps.setString(4,tm.getText());
            ps.setString(5,td.getText());
            ps.setString(6,tnc.getText());
            ps.setString(1,nBillId.format(nSysDate));
            res=ps.executeUpdate();
            if(res!=0 )
            {
                this.dispose();
                res=0;
                ps.close();
                co.close();
                JOptionPane.showMessageDialog(null,"Number Register Succesfull");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Registration Failed");
                     
            }
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NoRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combobox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField td;
    private javax.swing.JTextField tm;
    private javax.swing.JTextField tnc;
    private javax.swing.JTextField tno;
    private javax.swing.JTextField uid;
    // End of variables declaration//GEN-END:variables
}
